// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Component1$Frontend = require("./Component1.js");
var Component2$Frontend = require("./Component2.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component1$Frontend.make("Hello! Click this text.", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component2$Frontend.make("Hello!", /* array */[])), "index2");

/*  Not a pure module */
