// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var UserSelector$Frontend = require("./UserSelector.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, UserSelector$Frontend.make(/* array */[])), "root");

/*  Not a pure module */
