// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var getBaseUrl = (
    function () {
      var cfg = window.__serverFetchConfig;
      if (typeof(cfg) !== "undefined") {
        return cfg.scheme + "://" + cfg.host + ":" + cfg.port;
      } else {
        return "";
      }
    }
  );

var config = /* record */[/* baseUrl */"http://localhost:8001"];

exports.getBaseUrl = getBaseUrl;
exports.config = config;
/* getBaseUrl Not a pure module */
