// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

var getBaseUrl = (
    function () {
      var cfg = window.__frontendConfig;
      if (typeof(cfg) !== "undefined") {
        return cfg.scheme + "://" + cfg.host + ":" + cfg.port;
      } else {
        return "";
      }
    }
  );

var config = /* record */[/* baseUrl */Curry._1(getBaseUrl, /* () */0)];

exports.getBaseUrl = getBaseUrl;
exports.config = config;
/* getBaseUrl Not a pure module */
