// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ServerFetch$Frontend = require("./ServerFetch.js");
var ServerFetchConfig$Frontend = require("./ServerFetchConfig.js");

function usernameToString(username) {
  return username[0];
}

var baseUrl = ServerFetchConfig$Frontend.config[/* baseUrl */0];

var Fetch = ServerFetch$Frontend.MakeServerFetch(/* module */[/* baseUrl */baseUrl]);

function initialState(param) {
  return /* record */[/* users : array */[]];
}

function reducer(action, state) {
  if (action.tag) {
    return /* NoUpdate */0;
  } else {
    return /* Update */Block.__(0, [/* record */[/* users */action[0]]]);
  }
}

var component = ReasonReact.reducerComponent("UserSelector");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              Curry._1(Fetch[/* getUsers */4], /* () */0).then((function (rUsers) {
                      Curry._1(self[/* send */3], /* UpdateUsers */Block.__(0, [rUsers]));
                      return Promise.resolve(/* () */0);
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              return React.createElement("div", undefined, $$Array.map((function (user) {
                                return React.createElement("div", {
                                            onClick: (function (param) {
                                                return Curry._1(send, /* ShowUserTodos */Block.__(1, [user[/* entityKey */0]]));
                                              })
                                          }, user[/* entityValue */1][/* username */0][0]);
                              }), param[/* state */1][/* users */0]));
            }),
          /* initialState */initialState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.usernameToString = usernameToString;
exports.Fetch = Fetch;
exports.initialState = initialState;
exports.reducer = reducer;
exports.component = component;
exports.make = make;
/* Fetch Not a pure module */
