name: ocaml-export
version: 0.6.0.0
synopsis: Convert Haskell types in OCaml types
description: README.md
category: Web
author: James M.C. Haver II
maintainer: james.haver@plowtech.net
copyright: 2017 Plow Technologies
license: BSD3
github: plow-technologies/ocaml-export

library:
  source-dirs: src
  exposed-modules: 
  - OCaml.Export
  - OCaml.BuckleScript.Decode
  - OCaml.BuckleScript.Encode
  - OCaml.BuckleScript.Record
  - OCaml.BuckleScript.Spec
  - OCaml.BuckleScript.Types
  # Internal packages
  - OCaml.Internal.Common  
  - OCaml.BuckleScript.Internal.Spec
  - OCaml.BuckleScript.Internal.Module
  - OCaml.BuckleScript.Internal.Package  
  dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - directory
  - file-embed
  - filepath
  - formatting
  - hspec-golden-aeson >= 0.4.0.0
  - mtl
  - split
  - QuickCheck
  - quickcheck-arbitrary-adt
  - servant
  - servant-server
  - text
  - template-haskell
  - time
  - typelits-witnesses
  - wl-pprint-text
  ghc-options:
  - -Wall
#  - -Werror
#  - -Wredundant-constraints
#  - -fprint-potential-instances

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - aeson
    - bytestring
    - constraints
    - containers
    - directory
    - filepath
    - hspec
    - hspec-golden-aeson
    - ocaml-export
    - process
    - QuickCheck
    - quickcheck-arbitrary-adt
    - servant
    - servant-server
    - template-haskell
    - text
    - time
    - wai
    - wai-extra
    - warp
    - typelits-witnesses
    ghc-options:
    - -Wall
#    - -Werror
