name: ocaml-export
version: 0.6.1.0
synopsis: Convert Haskell types in OCaml types
description: Use GHC.Generics and Typeable to convert Haskell types to OCaml types. Convert aeson serialization to ocaml.
category: Web
author: James M.C. Haver II
maintainer: james.haver@plowtech.net
copyright: 2017 Plow Technologies
license: BSD3
github: plow-technologies/ocaml-export

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- directory
- filepath
- hspec
- hspec-golden-aeson >= 0.4.0.0
- QuickCheck
- quickcheck-arbitrary-adt
- servant
- servant-server
- text
- template-haskell < 2.12.0.0
- time
- typelits-witnesses
ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src
  exposed-modules: 
  - OCaml.Export
  - OCaml.BuckleScript.Decode
  - OCaml.BuckleScript.Encode
  - OCaml.BuckleScript.Record
  - OCaml.BuckleScript.Spec
  - OCaml.BuckleScript.Types
  # Internal packages
  - OCaml.Internal.Common  
  - OCaml.BuckleScript.Internal.Spec
  - OCaml.BuckleScript.Internal.Module
  - OCaml.BuckleScript.Internal.Package  
  dependencies:
  - file-embed
  - formatting
  - mtl
  - split
  - wl-pprint-text
  ghc-options:
  - -Wredundant-constraints
  - -fprint-potential-instances

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - ocaml-export
    - process
    - wai
    - wai-extra
    - warp
