name: ocaml-export
version: 0.1.0.0
synopsis: Collect statistics for all plowtech servers
description: README.md
category: Web
author: James M.C. Haver II
maintainer: james.haver@plowtech.net
copyright: 2017 Plow Technologies
license: BSD3
github: plow-technologies/ocaml-export

library:
  source-dirs: src
  exposed-modules: 
  - OCaml.Common
  - OCaml.Export
  - OCaml.File
  - OCaml.BuckleScript.Decode
  - OCaml.BuckleScript.Encode
  - OCaml.BuckleScript.Record  
  - OCaml.BuckleScript.Spec
  - OCaml.BuckleScript.Types
  dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - directory
  - file-embed
  - filepath
  - formatting
  - mtl
  - servant
  - text
  - template-haskell
  - time
  - typelits-witnesses
  - wl-pprint-text
  ghc-options:
  - -Wall
#  - -Werror
  - -fprint-potential-instances
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - aeson
    - bytestring
    - constraints
    - directory
    - filepath
    - hspec
    - hspec-golden-aeson
    - ocaml-export
    - process
    - QuickCheck
    - quickcheck-arbitrary-adt
    - servant
    - servant-server
    - servant-in-and-out
    - template-haskell
    - text
    - time
    - wai
    - wai-extra
    - warp
    ghc-options:
    - -fprint-potential-instances
